// Removed/visualize-superset/frontend/src/components/SupersetEmbed/SupersetEmbed.tsx
/**
 * Component for embedding Superset dashboards and charts.
 */

import { useEffect, useRef, useState, useCallback } from 'react';
import { embedDashboard } from '@superset-ui/embedded-sdk';
import { Box, CircularProgress, Typography, Alert, Paper } from '@mui/material';
import { supersetService } from '@/services/superset';

const SUPERSET_URL = import.meta.env.VITE_SUPERSET_URL || 'http://localhost:8088';

interface SupersetEmbedProps {
  type: 'dashboard' | 'chart';
  id: string;
  height?: string | number;
  filters?: Record<string, any>;
}

export function SupersetEmbed({
  type,
  id,
  height = '600px',
  filters: _filters,
}: SupersetEmbedProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  // Note: _filters can be used in future for dashboard filter presets
  void _filters;

  const fetchGuestToken = useCallback(async () => {
    try {
      // For demo purposes, we'll use environment variables for credentials
      // In production, this should be handled by a backend service
      const username = import.meta.env.VITE_SUPERSET_USERNAME || 'admin';
      const password = import.meta.env.VITE_SUPERSET_PASSWORD || 'admin';

      // Login to get access token
      const loginResponse = await supersetService.loginToSuperset(
        username,
        password
      );

      // Get guest token for the specific resource
      let guestToken: string;
      if (type === 'dashboard') {
        guestToken = await supersetService.getDashboardGuestToken(
          loginResponse.access_token,
          id
        );
      } else {
        guestToken = await supersetService.getChartGuestToken(
          loginResponse.access_token,
          id
        );
      }

      return guestToken;
    } catch (err) {
      console.error('Failed to fetch guest token:', err);
      throw new Error('Failed to authenticate with Superset');
    }
  }, [type, id]);

  useEffect(() => {
    let isMounted = true;

    const initEmbed = async () => {
      if (!containerRef.current) return;

      try {
        setLoading(true);
        setError(null);

        if (type === 'dashboard') {
          // Use Superset embedded SDK for dashboards
          await embedDashboard({
            id,
            supersetDomain: SUPERSET_URL,
            mountPoint: containerRef.current,
            fetchGuestToken,
            dashboardUiConfig: {
              hideTitle: false,
              hideChartControls: false,
              hideTab: false,
              filters: {
                visible: true,
                expanded: false,
              },
            },
          });
        } else {
          // For charts, we embed via iframe with guest token
          const token = await fetchGuestToken();

          if (containerRef.current && isMounted) {
            // Clear container using DOM methods
            while (containerRef.current.firstChild) {
              containerRef.current.removeChild(containerRef.current.firstChild);
            }

            // Create and append iframe safely
            const iframe = document.createElement('iframe');
            // Build URL safely using URL API
            const embedUrl = new URL('/superset/explore/', SUPERSET_URL);
            embedUrl.searchParams.set('standalone', 'true');
            embedUrl.searchParams.set('guest_token', token);
            embedUrl.searchParams.set('slice_id', id);

            iframe.src = embedUrl.toString();
            iframe.style.width = '100%';
            iframe.style.height = '100%';
            iframe.style.border = 'none';
            iframe.allow = 'fullscreen';
            iframe.sandbox.add('allow-scripts', 'allow-same-origin', 'allow-forms');

            containerRef.current.appendChild(iframe);
          }
        }

        if (isMounted) {
          setLoading(false);
        }
      } catch (err) {
        console.error('Failed to embed Superset:', err);
        if (isMounted) {
          setError(
            err instanceof Error
              ? err.message
              : 'Failed to load embedded content'
          );
          setLoading(false);
        }
      }
    };

    initEmbed();

    return () => {
      isMounted = false;
    };
  }, [type, id, fetchGuestToken]);

  if (error) {
    return (
      <Paper sx={{ p: 3 }}>
        <Alert severity="error">
          <Typography variant="body1" gutterBottom>
            Failed to load {type}
          </Typography>
          <Typography variant="body2" color="text.secondary">
            {error}
          </Typography>
        </Alert>
      </Paper>
    );
  }

  return (
    <Box
      sx={{
        position: 'relative',
        width: '100%',
        height,
        bgcolor: 'background.paper',
        borderRadius: 1,
        overflow: 'hidden',
      }}
    >
      {loading && (
        <Box
          sx={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            bgcolor: 'background.paper',
            zIndex: 1,
          }}
        >
          <CircularProgress />
          <Typography sx={{ ml: 2 }} color="text.secondary">
            Loading {type}...
          </Typography>
        </Box>
      )}
      <Box
        ref={containerRef}
        sx={{
          width: '100%',
          height: '100%',
          '& iframe': {
            width: '100%',
            height: '100%',
          },
        }}
      />
    </Box>
  );
}

// visualize-oblique/src/app/components/superset-embed/superset-embed.component.ts
import { Component, Input, OnInit, OnDestroy, ElementRef, ViewChild, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatCardModule } from '@angular/material/card';
import { SupersetService } from '../../services/superset.service';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-superset-embed',
  standalone: true,
  imports: [CommonModule, MatProgressSpinnerModule, MatCardModule],
  template: `
    <div class="superset-embed-container" [style.height]="height">
      @if (loading()) {
        <div class="loading-overlay">
          <mat-spinner diameter="40"></mat-spinner>
          <span class="loading-text">Loading {{ type }}...</span>
        </div>
      }

      @if (error()) {
        <mat-card class="error-card">
          <mat-card-content>
            <div class="error-icon">!</div>
            <h3>Failed to load {{ type }}</h3>
            <p>{{ error() }}</p>
            <p class="error-hint">
              Make sure Superset is running at {{ supersetUrl }} and the {{ type }} with ID "{{ id }}" exists.
            </p>
          </mat-card-content>
        </mat-card>
      }

      <div #embedContainer class="embed-container" [class.hidden]="loading() || error()"></div>
    </div>
  `,
  styles: [`
    .superset-embed-container {
      position: relative;
      width: 100%;
      min-height: 400px;
      background: #f5f5f5;
      border-radius: 8px;
      overflow: hidden;
    }

    .loading-overlay {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      background: rgba(255, 255, 255, 0.9);
      z-index: 10;
    }

    .loading-text {
      margin-top: 16px;
      color: #666;
    }

    .error-card {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      max-width: 400px;
      text-align: center;
    }

    .error-icon {
      width: 48px;
      height: 48px;
      margin: 0 auto 16px;
      background: #ff4d4f;
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 24px;
      font-weight: bold;
    }

    .error-card h3 {
      margin: 0 0 8px;
      color: #333;
    }

    .error-card p {
      margin: 0 0 8px;
      color: #666;
    }

    .error-hint {
      font-size: 12px;
      color: #999;
    }

    .embed-container {
      width: 100%;
      height: 100%;
    }

    .embed-container.hidden {
      visibility: hidden;
    }

    .embed-container iframe {
      width: 100%;
      height: 100%;
      border: none;
    }
  `]
})
export class SupersetEmbedComponent implements OnInit, OnDestroy {
  @Input() type: 'dashboard' | 'chart' = 'dashboard';
  @Input() id!: string;
  @Input() height = '600px';

  @ViewChild('embedContainer', { static: true }) embedContainer!: ElementRef<HTMLDivElement>;

  loading = signal(true);
  error = signal<string | null>(null);

  supersetUrl = environment.supersetUrl || 'http://localhost:8088';

  constructor(private supersetService: SupersetService) {}

  ngOnInit(): void {
    this.loadEmbed();
  }

  ngOnDestroy(): void {
    // Clean up iframe using safe DOM methods
    if (this.embedContainer?.nativeElement) {
      this.clearContainer();
    }
  }

  private clearContainer(): void {
    const container = this.embedContainer.nativeElement;
    while (container.firstChild) {
      container.removeChild(container.firstChild);
    }
  }

  private loadEmbed(): void {
    this.loading.set(true);
    this.error.set(null);

    // Get guest token from Superset
    this.supersetService.authenticateAndGetGuestToken(this.id, this.type).subscribe({
      next: (guestToken) => {
        this.createEmbed(guestToken);
      },
      error: (err) => {
        console.error('Failed to get guest token:', err);
        this.error.set(err.message || 'Failed to authenticate with Superset');
        this.loading.set(false);
      }
    });
  }

  private createEmbed(guestToken: string): void {
    const container = this.embedContainer.nativeElement;

    // Clear any existing content using safe DOM methods
    this.clearContainer();

    // Create iframe element
    const iframe = document.createElement('iframe');

    if (this.type === 'dashboard') {
      // For dashboards, use dashboard URL
      const embedUrl = new URL(`/superset/dashboard/${this.id}/`, this.supersetUrl);
      embedUrl.searchParams.set('standalone', 'true');
      embedUrl.searchParams.set('guest_token', guestToken);
      iframe.src = embedUrl.toString();
    } else {
      // For charts, use explore URL
      const embedUrl = new URL('/superset/explore/', this.supersetUrl);
      embedUrl.searchParams.set('standalone', 'true');
      embedUrl.searchParams.set('guest_token', guestToken);
      embedUrl.searchParams.set('slice_id', this.id);
      iframe.src = embedUrl.toString();
    }

    // Set iframe attributes
    iframe.style.width = '100%';
    iframe.style.height = '100%';
    iframe.style.border = 'none';
    iframe.allow = 'fullscreen';

    iframe.onload = () => {
      this.loading.set(false);
    };

    iframe.onerror = () => {
      this.error.set(`Failed to load ${this.type} iframe`);
      this.loading.set(false);
    };

    container.appendChild(iframe);
  }
}
